/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tonder;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


@SpringBootApplication
public class TonderApp {

    public static void main(String[] args) {
        SpringApplication.run(TonderApp.class);
    }
}
